### ISSUE TITLE
bench: S.js tests creating 2 computations per node

### ISSUE THREAD

**Issue by adamhaile** [maverick-js/observables#11]
Hi, I'm the author of [S.js.](https://github.com/adamhaile/S).  I learned about your framework and its benchmark when it was mentioned in a twitter conversation: https://twitter.com/RyanCarniato/status/1574305237933821953 .

I noticed that your benchmark for S.js has it doing 2x the work of the other implementations, as it's creating a second, unnecessary computation for each node.  Specifically, this line is redundant and should be removed.

```
        S(props.a), S(props.b), S(props.c), S(props.d);
```
 
 `props.a/b/c/d` are already computations.  Wrapping them a second time with `S(...)` makes a second, unnecessary computation out of those computations.

I don't know the history of this benchmark and gather that you may have copied it from somewhere else.  If the upstream source has the same issue, would you mind pointing me towards it, so that I can get it fixed there too?  Thanks!

**Comment by mihar-22** [comment]
Hey @adamhaile! 

Thanks for bringing this up as I wasn't aware, sorry for misrepresenting S.js! I'll get that fixed and updated ASAP. I had ported this over from a CodeSandbox and turned it in to a runnable bench in Node. Some libs have decided to use as it well but I'm not sure whether they're using it privately or not - can't find anything. I think it's safe to say for now that we only need to update here.

**Comment by adamhaile** [comment]
Thanks!
