### ISSUE TITLE
Small bug in this fallback

### ISSUE THREAD

**Issue by mindplay-dk** [maverick-js/observables#2]
This line:

https://github.com/maverick-js/observables/blob/522c526fd63c0c8a1a6e47f410e754bd6ee60213/src/scheduler.ts#L25

This fallback won't work - if `queueMicrotask` not defined, it will fail.

You need something like `window.queueMicrotask`, or more likely something like `typeof queueMicrotask != 'undefined'` to remain compatible with Node.

Very nice implementation of observables! Very small and very readable codebase. 🙂🙏

**Comment by mihar-22** [comment]
> This fallback won't work - if queueMicrotask not defined, it will fail.

Thanks heaps for catching that @mindplay-dk! I've made this mistake before 😅 

> Very nice implementation of observables! Very small and very readable codebase. 🙂🙏

😄 👍

**Comment by mindplay-dk** [comment]
Yep, we all have to make this mistake at least a dozen times 😅
